// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:376


#include "CommanderTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "CommanderTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Commander::CommandTypeSupport.

Commander::CommandTypeSupport_ptr
TAO::Objref_Traits<Commander::CommandTypeSupport>::duplicate (
    Commander::CommandTypeSupport_ptr p)
{
  return Commander::CommandTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Commander::CommandTypeSupport>::release (
    Commander::CommandTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Commander::CommandTypeSupport_ptr
TAO::Objref_Traits<Commander::CommandTypeSupport>::nil (void)
{
  return Commander::CommandTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Commander::CommandTypeSupport>::marshal (
    const Commander::CommandTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Commander::CommandTypeSupport::CommandTypeSupport (void)
{}

Commander::CommandTypeSupport::~CommandTypeSupport (void)
{
}

Commander::CommandTypeSupport_ptr
Commander::CommandTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return CommandTypeSupport::_duplicate (
      dynamic_cast<CommandTypeSupport_ptr> (_tao_objref)
    );
}

Commander::CommandTypeSupport_ptr
Commander::CommandTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return CommandTypeSupport::_duplicate (
      dynamic_cast<CommandTypeSupport_ptr> (_tao_objref)
    );
}

Commander::CommandTypeSupport_ptr
Commander::CommandTypeSupport::_nil (void)
{
  return 0;
}

Commander::CommandTypeSupport_ptr
Commander::CommandTypeSupport::_duplicate (CommandTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Commander::CommandTypeSupport::_tao_release (CommandTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Commander::CommandTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Commander/CommandTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Commander::CommandTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Commander/CommandTypeSupport:1.0";
}

::CORBA::Boolean
Commander::CommandTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Commander::CommandDataWriter.

Commander::CommandDataWriter_ptr
TAO::Objref_Traits<Commander::CommandDataWriter>::duplicate (
    Commander::CommandDataWriter_ptr p)
{
  return Commander::CommandDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Commander::CommandDataWriter>::release (
    Commander::CommandDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Commander::CommandDataWriter_ptr
TAO::Objref_Traits<Commander::CommandDataWriter>::nil (void)
{
  return Commander::CommandDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Commander::CommandDataWriter>::marshal (
    const Commander::CommandDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Commander::CommandDataWriter::CommandDataWriter (void)
{}

Commander::CommandDataWriter::~CommandDataWriter (void)
{
}

Commander::CommandDataWriter_ptr
Commander::CommandDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return CommandDataWriter::_duplicate (
      dynamic_cast<CommandDataWriter_ptr> (_tao_objref)
    );
}

Commander::CommandDataWriter_ptr
Commander::CommandDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return CommandDataWriter::_duplicate (
      dynamic_cast<CommandDataWriter_ptr> (_tao_objref)
    );
}

Commander::CommandDataWriter_ptr
Commander::CommandDataWriter::_nil (void)
{
  return 0;
}

Commander::CommandDataWriter_ptr
Commander::CommandDataWriter::_duplicate (CommandDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Commander::CommandDataWriter::_tao_release (CommandDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Commander::CommandDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Commander/CommandDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Commander::CommandDataWriter::_interface_repository_id (void) const
{
  return "IDL:Commander/CommandDataWriter:1.0";
}

::CORBA::Boolean
Commander::CommandDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Commander::CommandDataReader.

Commander::CommandDataReader_ptr
TAO::Objref_Traits<Commander::CommandDataReader>::duplicate (
    Commander::CommandDataReader_ptr p)
{
  return Commander::CommandDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Commander::CommandDataReader>::release (
    Commander::CommandDataReader_ptr p)
{
  ::CORBA::release (p);
}

Commander::CommandDataReader_ptr
TAO::Objref_Traits<Commander::CommandDataReader>::nil (void)
{
  return Commander::CommandDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Commander::CommandDataReader>::marshal (
    const Commander::CommandDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Commander::CommandDataReader::CommandDataReader (void)
{}

Commander::CommandDataReader::~CommandDataReader (void)
{
}

Commander::CommandDataReader_ptr
Commander::CommandDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return CommandDataReader::_duplicate (
      dynamic_cast<CommandDataReader_ptr> (_tao_objref)
    );
}

Commander::CommandDataReader_ptr
Commander::CommandDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return CommandDataReader::_duplicate (
      dynamic_cast<CommandDataReader_ptr> (_tao_objref)
    );
}

Commander::CommandDataReader_ptr
Commander::CommandDataReader::_nil (void)
{
  return 0;
}

Commander::CommandDataReader_ptr
Commander::CommandDataReader::_duplicate (CommandDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Commander::CommandDataReader::_tao_release (CommandDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Commander::CommandDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Commander/CommandDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Commander::CommandDataReader::_interface_repository_id (void) const
{
  return "IDL:Commander/CommandDataReader:1.0";
}

::CORBA::Boolean
Commander::CommandDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

