/* -*- C++ -*- */
/* Generated by S:\OpenDDS\bin\opendds_idl version 3.12 (ACE version 6.2a_p14) running on input file Commander.idl */
#ifndef OPENDDS_IDL_GENERATED_COMMANDERTYPESUPPORTIMPL_H_E49WOF
#define OPENDDS_IDL_GENERATED_COMMANDERTYPESUPPORTIMPL_H_E49WOF
#include "CommanderC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "CommanderTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Commander */



/* Begin STRUCT: Command */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const Commander::Command& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const Commander::Command& stru);

bool operator>>(Serializer& strm, Commander::Command& stru);

size_t gen_max_marshaled_size(const Commander::Command& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const Commander::Command> stru, bool align);

void gen_find_size(KeyOnly<const Commander::Command> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const Commander::Command> stru);

bool operator>>(Serializer& strm, KeyOnly<Commander::Command> stru);

template <>
struct MarshalTraits<Commander::Command> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Commander {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  Command_OpenDDS_KeyLessThan {
  bool operator()(const Commander::Command& v1, const Commander::Command& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.id < v2.id) return true;
    if (v2.id < v1.id) return false;
    return false;
  }
};
}


namespace Commander {
class CommandTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<Commander::Command> {
  typedef Commander::Command MessageType;
  typedef Commander::CommandSeq MessageSequenceType;
  typedef Commander::CommandTypeSupport TypeSupportType;
  typedef Commander::CommandTypeSupportImpl TypeSupportTypeImpl;
  typedef Commander::CommandDataWriter DataWriterType;
  typedef Commander::CommandDataReader DataReaderType;
  typedef Commander::Command_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "Commander::Command"; }
  static bool gen_has_key () { return true; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Commander {
class  CommandTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<CommandTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<Command> TraitsType;
  typedef CommandTypeSupport TypeSupportType;
  typedef CommandTypeSupport::_var_type _var_type;
  typedef CommandTypeSupport::_ptr_type _ptr_type;

  CommandTypeSupportImpl() {}
  virtual ~CommandTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static CommandTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<Commander::Command>();
bool gen_skip_over(Serializer& ser, Commander::Command*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: Command */

/* End MODULE: Commander */
#endif /* OPENDDS_IDL_GENERATED_COMMANDERTYPESUPPORTIMPL_H_E49WOF */
